name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash

    - name: Install Dependencies
      run: bun install

    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.4.7
      with:
        source: ./public/assets/styles/*.sass
        destination: ./public/assets/styles

    - name: Build
      run: bun run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./public

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        files: ./public/*
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}